function set_radioactivity()
  remote.call("kr-radioactivity", "add_item", "plutonium-fuel-cell")
  remote.call("kr-radioactivity", "add_item", "MOX-fuel-cell")
  remote.call("kr-radioactivity", "add_item", "breeder-fuel-cell")
  remote.call("kr-radioactivity", "add_item", "plutonium-238")
  remote.call("kr-radioactivity", "add_item", "plutonium-239")
  remote.call("kr-radioactivity", "add_item", "plutonium-fuel")
  remote.call("kr-radioactivity", "add_item", "depleted-plutonium-fuel-cell")
  remote.call("kr-radioactivity", "add_item", "depleted-MOX-fuel-cell")
  remote.call("kr-radioactivity", "add_item", "depleted-breeder-fuel-cell")
  remote.call("kr-radioactivity", "add_item", "breeder-fuel-cell-waste-solution-barrel")
  remote.call("kr-radioactivity", "add_item", "uranium-fuel-cell-waste-solution-barrel")
end

script.on_init(set_radioactivity)
script.on_configuration_changed(set_radioactivity)
